### ISSUE TITLE
MS Edge (Legacy) cannot parse daily-iframe-esm.js module

### ISSUE THREAD

**Issue by dbanisimov** [daily-co/daily-js#102]
Edge throws an error while evaluating the module: `Expected identifier, string or number`. The ESM version is being used `daily-iframe-esm.js`.

This is a react app bundled with webpack. Edge version 44.20185.1000.0

Repro code: https://codesandbox.io/s/heuristic-archimedes-ocos5

**Comment by kwindla** [comment]
Hi,

Apologies for this. We need to look at how better to structure our builds and `package.json` to make it easier to support legacy Edge.

The current workaround is to specify the non-esm version of the library:

```
  "dependencies": {
    "@daily-co/daily-js/dist/daily-iframe": "0.9.992",
...
```

**Comment by adamthewan** [comment]
I can confirm that the above solution works

**Comment by markbackman** [comment]
The above issue was resolved, but is now no longer relevant as the legacy version of Edge is no longer supported. Daily supports Microsoft Edge 74 and above.
