### ISSUE TITLE
Audio issue on iOS

### ISSUE THREAD

**Issue by adamthewan** [daily-co/daily-js#103]
Audio cuts out on iOS intermittently and the user has to restart CallObject

**Comment by kwindla** [comment]
Hi,

iOS Safari has some bugs with audio track handling. The biggest ones are:

1. On older iOS devices (slower CPUs) playing more than one video element is likely to cause audio playout to sound "choppy."

2. Sometimes audio elements report that they are playing a track, but they do not output any sound. This does not happen very often, but it definitely happens. We're working on gathering more numbers and trying to find a way to detect this so we can restart the play operation.

Can you tell us a little more about when you're seeing audio cut out? How many people are in the call? Does this happen for all tracks or just one track? iOS devices and software versions?

Yours,
Kwin

**Comment by adamthewan** [comment]
Hi @kwindla , we spoke on the Daily intercom but I'll post it here as well for other people to see.

Audio cuts out sometimes when muting and unmuting. We had 5 people in the call, and it happened for some tracks, not all. But it's random which track seems to be muted.

iOS 13

**Comment by nicokant** [comment]
Hi, I've been experiencing the same problem,
a user reported that when he switched off audio he was no more able to hear anything, we were 5 people, but only a user reported this problem, he seems not to be able to hear anyone.

I'm asking which iOS version he's using

**Comment by mshwery** [comment]
Adding some context here, _outside of iOS but on a Mac, Chrome 92_:

We are using an iframe with `allow="autoplay"` and the `<audio autoplay playsinline controls />` tag actually shows that it's playing with volume at 100% but no sound can be heard. If I remove the iframe around the content, I visually see the same control indicators but actually hear the audio. Any ideas what might be going on there?

I suspect that this could be a Chrome bug, but it happens the same in Safari.

**Comment by mattieruth** [comment]
We have made many improvements to audio since this was last updated and believe this likely resolved. A new issue should be filed with updated details if this is still believed to be happening.
