### ISSUE TITLE
Extra arguments for join()

### ISSUE THREAD

**Issue by stubbies** [daily-co/daily-js#104]
It would be very useful for us if we could define our own participant user_id when doing `join()` or at least pass an extra data argument.

```
join({
  url: 'url',
  data: 'data-string'
})
```

And have this data returned in the participant object.

**Comment by kwindla** [comment]
Hi,

Thanks for the suggestion. We will look at implementing this.

You can pass `userName` to the `join()` call. You can also set a `user_id` field in a meeting token for each user.

Kwin

**Comment by stubbies** [comment]
Meeting token was what I needed, thanks.
