### ISSUE TITLE
getInputDevices returns audioinput device type for speaker

### ISSUE THREAD

**Issue by dbanisimov** [daily-co/daily-js#106]
`getInputDevices` instance method returns an incorrect device as the `speaker` device on the first call when no input devices were set before. I'm consistently getting the default microphone returned instead. After the device selection using `setOutputDevice` the returned speaker device is correct.

Repro code: https://codesandbox.io/s/daily-co-getinputdevices-repro-fzduq
Repro steps:

1. Provide a room URL at `INSERT_URL`
2. Click `create room`
3. Click `join meeting (as participant)`
4. See the output of `getInputDevices` under `devices info`

What happens: an `audioinput` kind of device will be listed under the `speaker` key
What is expected instead: an `audiooutput` device, or null/undefined if the browser doesn't support output devices selection

Browsers: Edge 85.0.564.36 (Chromium) on Win 10, Chrome 84 on Android

**Comment by markbackman** [comment]
This issue cannot be reproduced. It was likely resolved long ago. Calling `getInputDevices()` returns the following:
```
{
    "callFrameId": "17023896163570.45126687370552143",
    "camera": {
        "deviceId": "bfc83a8232d388dab973c636adf85603e99d173e11bd7f0198eeee617d066349",
        "kind": "videoinput",
        "label": "Logitech Webcam C930e (046d:0843)",
        "groupId": "3c3c0cca0cdc188586493d375667cf94730a6af0dfb010d187367b7b80280e2e"
    },
    "mic": {
        "deviceId": "c16843b237b1c463f5707234d9bee0b5e4e8418e5c60a0228abc221a268626f4",
        "kind": "audioinput",
        "label": "MacBook Pro Microphone (Built-in)",
        "groupId": "0cb15087d716cc1c1100c9fde255e93946012bb1eaa79f846244f49b23d39640"
    },
    "speaker": {
        "deviceId": "default",
        "kind": "audiooutput",
        "label": "Default - MacBook Pro Speakers (Built-in)",
        "groupId": "0cb15087d716cc1c1100c9fde255e93946012bb1eaa79f846244f49b23d39640"
    }
}
```

Closing this issue.
