### ISSUE TITLE
getInputDevices returns a non-Promise result when not joined

### ISSUE THREAD

**Issue by dbanisimov** [daily-co/daily-js#108]
`getInputDevices` returns a plain object instead of an immediately resolved promise when the meeting is in a non-joined state. This prevents the result from being used in a promise chain.

https://github.com/daily-co/daily-js/blob/e1b39076e7e4f44725155c6fbd878e4b4d2b3fa7/src/module.js#L679-L687

It would be good to make it consistent with the regular return value, or at least update the [docs](https://docs.daily.co/reference#%EF%B8%8F-getinputdevices) stating this special case

**Comment by Regaddi** [comment]
This issue was resolved with https://github.com/daily-co/daily-js/commit/67ab71d20d84d0b7a24ddee0131993848b9df056
