### ISSUE TITLE
.on() listener from callObject delayed trigger on receiving side

### ISSUE THREAD

**Issue by realesh** [daily-co/daily-js#111]
Ran into this issue when using custom UI through `createCallObject()` as explained here
[https://www.daily.co/blog/building-a-custom-video-chat-app-with-react/](url)

It seems like every listener triggered 1+ seconds late in the receiving side (such as muting / unmuting)
there's a significant delay when participant started talking right after unmuting their audio, so that some of the voice got cut off.

`react` version: "^16.13.1"
`@daily-co/daily-js` version: "^0.9.992"

**Comment by adamthewan** [comment]
Here's a video for the issue we faced:
https://www.loom.com/share/3c95744e3acf4b9b971b80d444b9d028

**Comment by adamthewan** [comment]
Hey guys, we didn't solve the `.on` event delay. However for muting and unmuting specifically, we managed to solve it by managing our `audioTrack` like this:

```
/**
   * When audio track changes, update audio srcObject
   */
  useEffect(() => {
    audioEl.current &&
      audioTrack &&
      (audioEl.current.srcObject = new MediaStream([audioTrack]));
  }, [audioTrack]);
```

So that `audioEl.current.srcObject` doesn't get sent `undefined` `audioTrack`
