### ISSUE TITLE
Invalid State Error in Firefox

### ISSUE THREAD

**Issue by nicokant** [daily-co/daily-js#132]
I have a React application using Daily.co JS in iframe mode, I've implemented a custom button to start screen sharing, but when using in Firefox I receive the following error: `getDisplayMedia must be called from a user gesture handler.`

# Expected behavior
Calling `startScreenShare()` from an event handler should not trigger the error

# Describe the bug (unexpected behavior)
Calling `startScreenShare()` in firefox throws the following error: InvalidStateError getDisplayMedia must be called from a user gesture handler.
All the following calls  throws with error: The request is not allowed by the user agent or the platform in the current context.

# Steps to reproduce

This is a brief summary of my component:
```jsx
class DailyMeeting extends React.Component {
 
 async componentDidMount() {
   this.callFrame = DailyIframe.wrap(this.iframe);
   await this.callFrame.join({ this.props.meetingUrl })
 }
 
  startSharing = () => {
    this.callFrame.startScreenSharing();
  }

  render() {
    return (
      <>
         <iframe
                    frameBorder={0}
                    ref={r => this.iframe = r}
                    allow="camera;microphone;autoplay"
                    style={{
                        width: '100%',
                        height: 'calc(100vh - 128px)',
                    }}
                ></iframe>
         <button onClick={this.startSharing}>start sharing</button>
      </>
    )
  }
}
```

# System information 

 

* Device: MacBook Air
* OS, version: OSX 10.15
* Browser, version: Firefox 81

**Comment by philmillman** [comment]
Thanks for the bug report. Do you still get this error if you add `display-capture` to the `allow` attribute?

**Comment by nicokant** [comment]
Adding `display-capture` prevents the second error (`The request is not allowed by the user agent or the platform in the current context.`) to be thrown. Now I still get `getDisplayMedia must be called from a user gesture handler.` error at every click

**Comment by philmillman** [comment]
ok and to confirm: this is FF only?

**Comment by nicokant** [comment]
I'm not totally sure, right now I only tried FF and Chrome, in Chrome it works without any problem

**Comment by philmillman** [comment]
Ok, I'll escalate on our side. Feel free to reach out on Intercom if it's urgent.

**Comment by Regaddi** [comment]
As of today this seems to not be an issue anymore. I vaguely remember having a conversation about this issue, but that's a while ago obviously. Closing now.

**Comment by Ezhil-Git** [comment]
This is happening in safari browser.

`[Error] Error starting ScreenShare: unknown: InvalidStateError: getDisplayMedia must be called from a user gesture handler.
	value (Anonymous Script 1 (line 4:178082))
	value (Anonymous Script 1 (line 4:179892))
	D (Anonymous Script 1 (line 4:407258))
	(anonymous function) (Anonymous Script 1 (line 4:405486))
`

**Comment by mattieruth** [comment]
> This is happening in safari browser.
> 
> `[Error] Error starting ScreenShare: unknown: InvalidStateError: getDisplayMedia must be called from a user gesture handler. value (Anonymous Script 1 (line 4:178082)) value (Anonymous Script 1 (line 4:179892)) D (Anonymous Script 1 (line 4:407258)) (anonymous function) (Anonymous Script 1 (line 4:405486)) `

This is a known quirk of safari. Safari is very strict when it comes to screensharing and as the error indicates, the act requires `getDisplayMedia()` to be called as a direct result of a user action (like clicking a button). There is no work-around to simulate this.
