### ISSUE TITLE
Missing userName property in DailyCallOptions type definition

### ISSUE THREAD

**Issue by grokasm** [daily-co/daily-js#154]
# Expected behavior
The documentation states that the participant username can be set on the call object from either the `createCallObject` or `join` calls.

It is expected to be able to pass in a `userName` property [as described in the docs](https://docs.daily.co/reference#properties)

# Describe the bug (unexpected behavior)

The type definition for `DailyCallOptions` does not define a `userName` property.

**Comment by Regaddi** [comment]
This was fixed long time ago https://github.com/daily-co/daily-js/commit/f2609ce7cccbf35aa014884e2650fa9331b3dbda, but I seem to have forgotten about this issue. Closing as fixed.
