### ISSUE TITLE
🐛 meetings not working on latest chrome on iOS

### ISSUE THREAD

**Issue by a-tokyo** [daily-co/daily-js#156]
# Expected behavior
Latest chrome on iOS should be able to smoothly host meetings

# Describe the bug (unexpected behavior)

Meetings do not work on latest chrome on latest iOS.

# Steps to reproduce

Go to any meeting room using chrome on iOS.

# Screenshots

![image](https://user-images.githubusercontent.com/12428415/108881490-0b86c980-760c-11eb-813e-b8f3b867e88e.jpeg)
![image](https://user-images.githubusercontent.com/12428415/108881478-06c21580-760c-11eb-8234-90dd310b9018.png)
# System information 

* Device: iPhone 7
* OS, version: iOS 14.4
* Browser, version: chrome 87 latest - attached exact version as a screenshot

# Additional context

Works smoothly on Safari
Room has signaling_impl="ws"

**Comment by kompfner** [comment]
For now we aren't yet supporting non-Safari usage on iOS.

But you're totally right that the previous technical limitation preventing us from making calls in a WKWebView should've been lifted in the most recent versions of iOS! It's on our roadmap to see if we can enable this and test on various browsers—thanks for your patience!

Also, yes, it appears that our error message in this case is quite misleading. Apologies!

**Comment by timsaval** [comment]
@kompfner Interesting! Would be very useful to get this fixed. Please give us a rough time estimate for fixing these. 🚀

**Comment by A-Tokyo** [comment]
@kompfner Thanks for the response! We will be waiting for this!

**Comment by A-Tokyo** [comment]
Update: Still not working, but now it shows this message:  (Refreshing doesn't trigger the permissions request popup.)

![IMG_2317](https://user-images.githubusercontent.com/12428415/111394996-86e81200-86c4-11eb-9537-dc477467d6c7.jpeg)

**Comment by kompfner** [comment]
Hmm...I take it that when you go to Settings -> Chrome, you do see that Chrome has Camera and Microphone permissions?

**Comment by A-Tokyo** [comment]
@kompfner I can see the camera and mic in settings, they are enabled. Chrome still shows the message above when joining a daily meeting, even if all the permissions were granted. Sidenote: works perfectly on Safari.

**Comment by alexkunger** [comment]
it seems that Chrome <= 92 and Safari <= 11 don't work still
they have an error `'navigator.mediaDevices.addEventListener' is undefined`
any chance this will get fixed?

**Comment by markbackman** [comment]
Daily calls run as expected on iOS in Chrome and Safari browsers. Calling [`supportedBrowser()`](https://docs.daily.co/reference/daily-js/static-methods/supported-browser) is recommended as a way to ensure that a given browser and version is supported.

Supported browsers list: https://docs.daily.co/guides/how-daily-works/browsers.

The minimum version on iOS is 12.1. Note that Safari and Chrome on iOS run on the same engine, so both have a minimum version of 12.1. Why 12.1? WebRTC wasn't fully supported on iOS Safari until then.
