### ISSUE TITLE
🐛 Camera frozen and reversed on react-native webview + meetings don't work

### ISSUE THREAD

**Issue by A-Tokyo** [daily-co/daily-js#157]
# Expected behavior

Camera view should look and behave just like it does on safari. Ie: not reversed, and live.
Users should be able to have meetings just like on web.

# Describe the bug (unexpected behavior)

If a meeting room is opened on react-native webview, the camera view freezes and is reversed.

# Steps to reproduce

Open a meeting room link in react-native using webview 

# Screenshots

![image](https://user-images.githubusercontent.com/12428415/108883017-9e743380-760d-11eb-9a2a-511654cd2fc4.png)

# System information 

* Device: iPhone 7
* OS, version: 14.4
* Browser, version: react-native@0.63.4 + webview@8

# Additional context

Works smoothly on Safari

**Comment by kompfner** [comment]
Until the latest versions of iOS calls were not supported in WKWebViews due to OS-level technical limitations, so we haven't yet supported web view usage. It's on our roadmap to do some testing and see what we can do to support web view usage going forward. Good catch, and thanks for the report!

**Comment by timsaval** [comment]
@kompfner  Interesting! Would be very useful to get this fixed. Please give us a rough time estimate for fixing these. 🚀

**Comment by A-Tokyo** [comment]
@kompfner Thanks for the response! We will be waiting for this!

**Comment by kompfner** [comment]
Let me preface by saying that we definitely have a bit of work to do to get our calls to detect that we're running in a web view that can make calls, and thus start appropriately. We have a fix for that that's currently being tested and reviewed.

That said, the issue described above doesn't appear to be related to that fix (it looks like the call already successfully starts!) Instead, it appears to be an issue with how the web view is configured. I don't personally have experience with react-native-webview or what configurability it exposes, but under the covers it must be using `WKWebView`. If you were using a raw `WKWebView`, you could avoid the issues you're seeing by adding the following two things to `WKWebViewConfiguration`:

```swift
let webConfiguration = WKWebViewConfiguration()
// ...do some configuration here...
webConfiguration.mediaTypesRequiringUserActionForPlayback = []
webConfiguration.allowsInlineMediaPlayback = true
```

**Comment by A-Tokyo** [comment]
@kompfner Thanks for the help ✨ 

The fix for `react-native-web-view` is to pass the prop `allowsInlineMediaPlayback`.

eg:
```js
<WebView
  /** pass baseUrl to avoid  `IntegrationError must use HTTPS.` error https://github.com/react-native-community/react-native-webview/issues/1317 */
  baseUrl=""
  source={{
    uri: room_url,
  }}
   /** Fixes frozen camera - https://github.com/daily-co/daily-js/issues/157#issuecomment-791849659 */
  allowsInlineMediaPlayback
  // ...rest
/>
```
