### ISSUE TITLE
Failed to load call object bundle https://c.daily.co/static/call-machine-object-bundle.js

### ISSUE THREAD

**Issue by dburdan** [daily-co/daily-js#166]
# Describe the bug (unexpected behavior)

When attempting to connect to a room on mobile (React Native), it returns `Failed to load call object bundle https://c.daily.co/static/call-machine-object-bundle.js: TypeError: Cannot read property 'prototype' of undefined`.

Appears to be related to this block of code: https://github.com/daily-co/daily-js/blob/main/src/CallObjectLoader.js#L280

# Steps to reproduce

Anytime we attempt to connect via `callObject.join` we get the error.

# System information 

Tested across several devices and simulators, both iOS and Android. 

# Additional context

Our setup was working previously on iOS but threw this error on Android. Now appears to be throwing for both platforms.

**Comment by kwindla** [comment]
Hi @dburdan. What version of daily-js are you using?

We can try to repro. Is there any chance that you have a minimal repro case handy?

**Comment by dburdan** [comment]
Hey @kwindla,

We are using `@daily-co/react-native-daily-js` v0.10.0. To be safe we also tried v0.8.0. Also using `@daily-co/react-native-webrtc` v1.75.8.

I don't have a repro available at the moment since it's baked into our mobile app, but if the issue isn't trivial I can work on getting one put together in a repo. I know it's not a lot to go on, so I will see what additional info I can find on the issue.

**Comment by dburdan** [comment]
Actually, that [code block](https://github.com/daily-co/daily-js/blob/main/src/CallObjectLoader.js#L280) above got me thinking about the dynamic code execution, and whether or not React Native's Hermes engine was playing a role in the error. When I disabled Hermes on iOS, it did not throw the error and instead connected successfully.

So it must have something to do with Hermes and that code execution. Let me know if there is any additional info I can provide to help fix.

**Comment by kwindla** [comment]
Ah, you beat me to it. After conferring internally, we were going to come back here to ask you whether you're using Hermes, which does indeed cause problems with our dynamic code execution. The short term fix is for us to build a version of our js bundle specifically targeting Hermes, which requires different transpilation.

We will schedule the work on this and post here with an expected ship date for that fix.

We're also working on a new architecture for our libraries that doesn't use dynamic execution at all, and allows us to replace react-native-webrtc with our own build of libwebrtc. That's a couple of months away, but will make the bundle smaller and allow you to build all of the code directly into your app.

**Comment by dburdan** [comment]
@kwindla Thanks so much for the info! I'll stay posted for the update here and inform our team about Hermes 👍🏼

**Comment by nalhusail** [comment]
@kwindla I'm facing the same issue as @dburdan, but using the daily-js front-end library on chrome extension

Basically, I'm building a chrome extension using Manifest version 3, and seems like I'm not allowed to download and evaluate js files after it starts running

Is there a way to download and embed call-machine-object-bundle.js in the resources directly instead of dynamically?

**Comment by nalhusail** [comment]
I tried to load the call-machine-object-bundle.js first in the manifest file, and got the following error on line 27
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```
should I create a separate issue for this? it's related to loading the same file, but on a different platform/sdk than OP

**Comment by aaronvg** [comment]
Same issue here but on Electron
