### ISSUE TITLE
BUG: `setUserName` method has no effect on custom call object

### ISSUE THREAD

**Issue by ariboren** [daily-co/daily-js#174]
# Expected behavior

Calling `callObject.setUserName('name')` should update the participant's name in their corresponding `DailyParticipant` object for all call participants. As stated in the docs, the method should return "a Promise which resolves to the name that was set."

# Describe the bug (unexpected behavior)

The method call has no effect, and the Promise does not return.

# Example code

```javascript
// Example from React implementation

useEffect(() => {
    console.log('>>> CREATING CALL OBJECT');

    const call = Daily.createCallObject({
        token,
        url: callUrl,
        ...DAILY_FACTORY_CONFIG,
    });

    setCall(call);
}, [token, callUrl]);

useEffect(() => {
    if (call) {
        console.log('>>> SETTING USER NAME', userName);

        call.setUserName(userName).then(({ userName }) => {
            // This never logs
            console.log('>>> SET USER NAME', userName);
        });
    }
}, [call, userName]);
```

At runtime, the Promise body is never logged:

```
>>> CREATING CALL OBJECT
>>> SETTING USER NAME Test
[Resolved promise log should be here]
```

# Daily version
v0.21.0

# Additional context

The call connects fine otherwise.

**Comment by Regaddi** [comment]
Hey @ariboren,

thank you very much for your report!
While your example code contains a good chunk of information, it'd be easier for us to verify the issue, if you provided a minimal reproduction; a codesandbox would be sufficient.

The Promise not resolving could be a side-effect of running the `useEffect` based on `userName` changes, assuming calling `callObject.setUserName` updates `userName` elsewhere in your code.

Thank you and apologies for the inconvenience!

Best,
Christian

**Comment by jasonejavier** [comment]
Hi. I'm also experiencing this. is there any resolution to this issue? hehe thank youuu

**Comment by jasonejavier** [comment]
Are there any updates regarding this issue? thank you

**Comment by Regaddi** [comment]
The issue in its current form has a lot of potential application-level issues.
In general we highly recommend integrating with https://github.com/daily-co/daily-react when building with React.

Without a minimal reproduction provided for the issue mentioned it is very very difficult for us to work on this.

We don't see any issues related to `setUserName` in [Daily Prebuilt](https://www.daily.co/products/prebuilt-video-call-app/), which in itself is a custom call object app built in React.

I'm closing this issue for now, but please let us know, when there's a minimal reproduction for the issue available.
