### ISSUE TITLE
Missing custom config value in DailyStreamingLayoutConfig type definition

### ISSUE THREAD

**Issue by ssimonitch** [daily-co/daily-js#189]
# Expected behavior

The documentation details a `custom` value as an available recording/streaming layout that can be set via options passed to the `startRecording` or `startLiveStreaming` methods:

https://docs.daily.co/reference/daily-js/instance-methods/start-recording#control-cloud-recording-layouts

# Describe the bug (unexpected behavior)

There is no support for `custom` layout in the `DailyStreamingLayoutConfig` type definition.

**Comment by mattieruth** [comment]
Thank you for this report! I believe this has now been resolved. Feel free to re-open if otherwise.
