### ISSUE TITLE
joined_at field on participant object returns unix epoch if local participant has not yet joined the room (preauth)

### ISSUE THREAD

**Issue by ssimonitch** [daily-co/daily-js#191]
# Expected behavior
When inspecting the local participant object after calling `preAuth` I expect the `joined_at` field to be `undefined` as the local participant has not yet joined the room and the typescript type specifies a `Date | undefined` type

# Describe the bug (unexpected behavior)
The `joined_at` field is a `Date` object with the value set to the unix epoch (Thu Jan 01 1970). I imagine that `undefined` is getting returned for this value but somewhere along the line it is still getting fed into the `Date` constructor.

# Steps to reproduce

1. call `preAuth` to get access to local participant information
2. call `participants` or similar to get the local participant data
3. inspect `joined_at` value

# Additional context

Using the react hooks library

**Comment by mattieruth** [comment]
This has now been released as part of 0.30.0 and will require an upgrade to that version to get the fix.
