### ISSUE TITLE
[FEATURE-REQUEST] Breakout rooms

### ISSUE THREAD

**Issue by JoseIsra** [daily-co/daily-js#203]
# Feature request

Hello daily bros, this is not a request itself but a consult, the breakout rooms already exist in the dailyjs API? Maybe with the prebuilt dailyjs or the custom ?

# Why you need this
Breakout rooms are a well known feature in the video chat apps/tools so that's why I'm asking this

Thanks for your time, i hope you can help me by giving me some advice or guide. Dailyjs is amazing, you have done a great tool :3

**Comment by markbackman** [comment]
Hi @JoseIsra, breakout rooms are already supported by daily-js. You have two options for how to build this feature: 1) You can utilize track subscriptions to create "sub-rooms" of participants, or 2) you can use separate Daily rooms as breakout rooms.

For option 1 (track subscriptions), your application logic will create groups of people who form a breakout room. People in each group only subscribe to audio and video tracks of others in the same room. You can learn more about track subscriptions here: [blog](https://www.daily.co/blog/create-dynamic-meetings-using-track-subscriptions/), [reference](https://docs.daily.co/reference/daily-js/instance-methods/update-participant#track-subscriptions).

For option 2 (separate rooms), the idea is that you'll use different Daily rooms for each breakout room. You will need to create a separate service that tracks participant state for each breakout room and manages the movement of participants between rooms. This is mostly new code that you'll have to write that exists outside of Daily's APIs, but we have some examples we can share to get you started.

We're happy to share more details about how to build for each of these cases. You can either reach out to support (https://www.daily.co/company/contact/support) or post on our developer community (https://community.daily.co).

Lastly, we are adding a breakout rooms feature to Daily Prebuilt. Expect to see a beta release of a breakout rooms feature available in Daily Prebuilt in the next month. Hope this helps!

Also, thanks for the kind words about our APIs! 😄
