### ISSUE TITLE
BUG: Fullscreen button doesn't work in prebuilt UI

### ISSUE THREAD

**Issue by fantoine** [daily-co/daily-js#209]
# Expected behavior

I expect the "fullscreen" button in the prebuilt UI to open the room in fullscreen.

# Describe the bug (unexpected behavior)

Since version 0.38.0 of `@daily-co/daily-js`, the fullscreen button doesn't do anything.

It does not open the room in fullscreen nor trigger any error.

I suspect [this commit](https://github.com/daily-co/daily-js/commit/43509d6ae5e151c52d835eacdd3f8a7a293be003) introduced this problem.

# Steps to reproduce

1. Go to any Daily room in a prebuilt UI
2. Click on the "fullscreen" anything
3. Nothing happens

# Screenshots

N/A

# System information 

 

* Device: MacBook
* OS, version: MacOS
* Browser, version: Brave, Chrome, Firefox, Safari...

# Additional context

N/A

**Comment by mattieruth** [comment]
Hi! Thank you for the report. This should be resolved in the latest release, 0.40.0.
