### ISSUE TITLE
BUG - Typo in DailyFactoryOptions type

### ISSUE THREAD

**Issue by ssimonitch** [daily-co/daily-js#210]
Hey guys, thanks for the great updates in 0.40.0

I noticed that the new TypeScript typedef for `DailyFactoryOptions` has a small mistake: the new `strictMode` property is incorrectly written as `srictMode`

**Comment by mattieruth** [comment]
Good catch! I'll file a ticket and get a patch ready for either a point release or at minimum the next release. Thanks!
