### ISSUE TITLE
[FEATURE-REQUEST] ability to set recording start time and end time

### ISSUE THREAD

**Issue by chr4ss12** [daily-co/daily-js#214]
I have read the documentation about ability to create recordings based on the meeting token, as well the room object itself having ability to create recording, and the recording API itself, but none seems to be as trivial to use as I would like for my specific use case.

I would like the room creation API have a simple way of saying:

"hey, create me a room, and by the way, please ensure you create a recording that starts at date X and ends at date Y, and save it into my cloud"

I would not like to deal with writing code to start orchestrating the automatic live recording myself with cron jobs

**Comment by mattieruth** [comment]
Thanks for the request! We've added this to our feature tracking.
