### ISSUE TITLE
Using experimentalChromeVideoMuteLightOff causes participant events to fire too many times.

### ISSUE THREAD

**Issue by tomasinkevicius** [daily-co/daily-js#216]
# Expected behavior

When turning off camera, camera light should turn off without participant-updated firing twice as many times as usually.

# Describe the bug (unexpected behavior)

As I understand only way to turn off the camera light after camera is turned off is to use `experimentalChromeVideoMuteLightOff`. After using stop() on the tracks you cannot start them again and there is no way to refresh them. 
Problem is that when using `experimentalChromeVideoMuteLightOff` `participant-updated` is firing a lot more times than it does without `experimentalChromeVideoMuteLightOff` causing my react app to lag because of too many rerenders.

# Steps to reproduce

Add `participant-updated` event in your app and console.log inside of it.
Set experimentalChromeVideoMuteLightOff to true.
Test console.logs before and after adding experimentalChromeVideoMuteLightOff.

# System information 

"react": "^17.0.2",

# Additional context

Usually lag in application is not noticeable with ~5 participants in a call but when there is ~20 it becomes impossible to use because of participant event's firing too many times.

**Comment by mattieruth** [comment]
Hi! Thanks for filing this. Unfortunately, I'm not able to reproduce this per your description and I think I need more context.
- What daily-js version are you experiencing this on?
- Is there a version where this doesn't happen?
- Is there an action or API call that triggers the `participant-updated` events to begin spamming or do they happen immediately upon joining?
- Are there other specifics you can share about your call setup?
- Can you share dashboard logs from a session that experienced this? (or if you want to share a domain + session id for me to pull them up, you can email help@daily.co, link to this ticket and say to pass it on to me :) )

Thanks!
~mattie ruth
