### ISSUE TITLE
#"></div><a href= http://evil.com>clickme</a 

### ISSUE THREAD

**Issue by ansamatemp** [daily-co/daily-js#218]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\SM\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\SM\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

<style>

</style>
</head>

<body link=blue vlink=purple>

#"></div><a href=   http://evil.com>clickme</a
--

</body>

</html>

**Comment by mattieruth** [comment]
![](https://media.giphy.com/media/pD7YIQoUwgb9cnX3FJ/giphy-downsized.gif)
