### ISSUE TITLE
error rejoining dailyifram in react after component unmount

### ISSUE THREAD

**Issue by dlinah** [daily-co/daily-js#22]
## what happens
on the second attempt to wrap ifram `DailyIframe.wrap(iframeRef)` and join metting, the iframe start without permission to mic or cam 
<img width="559" alt="Screenshot 2020-04-07 at 14 43 37" src="https://user-images.githubusercontent.com/24292074/78670668-66bda980-78de-11ea-87f0-80f8a61c5ce6.png">
console error
<img width="311" alt="Screenshot 2020-04-07 at 14 44 30" src="https://user-images.githubusercontent.com/24292074/78670693-6f15e480-78de-11ea-9867-f3b2df17b4d7.png">
## code
```


const dailyVideo = ({roomUrl}) => {

  const iframeRef = useRef(null);

  const run = () => {
    let daily = dailyInstance;
    if (!daily) {
      daily = DailyIframe.wrap(iframeRef.current);
      setDailyInstance(daily);
    }
    // join the room
    daily?.join({ url: roomUrl });
  };

  // destroy daily ifram on unmount
  const prevIsDailySet = useRef();
  useEffect(() => {
    prevIsDailySet.current = !!dailyInstance;
  });
  useEffect(() => {
    return () => {
      if (dailyInstance && prevIsDailySet.current) {
        dailyInstance.destroy();
      }
    };
  }, [!!dailyInstance]);
  // destroy daily ifram on unmount


  return (
    <div>
        <button onClick={() => run()}></button>
        <iframe
          title="video call iframe"
          ref={iframeRef}
          allow="camera; microphone; fullscreen;"
        />
    </div>
  );
};

```
## reproduce steps
*  load compoenet
* click join 
* reload compoenet : by navigation to another page in the app then comming back
* try joining again

**Comment by dlinah** [comment]
it turned out that the problem was that `dailyInstance.distroy()` does not get called correctly , react unmount before the instance is distroyed . so to insure that react waits for `distroy()` to finish , i put the `dailyInstance` in a global state , and destroy it on component mount instead

**Comment by kwindla** [comment]
That's a really good solution. We've seen this issue before and will look at our docs to see if we can improve how we explain/warn about it. (cc @joey-dailyco @philmillman)  Thank you!

**Comment by Regaddi** [comment]
For usage with React we highly recommend checking out https://github.com/daily-co/daily-react
