### ISSUE TITLE
[FEATURE-REQUEST] Ability to specify the recording parameters

### ISSUE THREAD

**Issue by chr4ss12** [daily-co/daily-js#220]
Currently it is not possible to specify recording parameters (quality, bitrate, whetever it is audio-only recording) when you create a meeting token with:

enable_recording:true
start_cloud_recording:true,

the audio is going to be recorded in 96kbps which is not enough for Spotify (320). (nor can I specify that it is audio-only)

I understand if I start using the startRecording() calls, I would be able to change all of this, but I very much would not like to start handling the recording process myself (when to stop, when to start), how to make sure there are no multiple recordings going on,  and yada yada.

**Comment by mattieruth** [comment]
Thank you! This will be supported in the next daily-js release (0.48.0).
