### ISSUE TITLE
right pattern to handle permissions?

### ISSUE THREAD

**Issue by chr4ss12** [daily-co/daily-js#224]
in a club-house like situation (just imagine clone of partyline), right now, when users join the event, they are prompted with permission dialog,  the users are able to raise the hand, and when made a speaker, they have option to unmute themselves, but this leaves us/them in a weird situation where IF they didn't give the permissions in the beginning, and when trying to unmute, it does not work for them.

At that point camera-error is thrown, but it is a bit too late, users should not be able to raise the hand before having sorted their microphone permissions.

Note when the permission dialog pops-up and they reject the permissions, no error is thrown by Daily, it is only when participant is trying to unmute.

What is the correct pattern of 'knowing' whenever user has granted permissions or not on WEB & APP.

Should I just call window.getUserMedia() with same parameters myself, before handraising and hope that it does not interfere with daily-co logic? not sure if I need to stop() all of the tracks I get from window.getUserMedia() as well, or leave it.

I have read

https://docs.daily.co/guides/configurations-and-settings/handling-device-permissions
https://www.daily.co/blog/how-to-show-device-permissions-errors-in-a-custom-daily-app/

but they don't help.

**Comment by mattieruth** [comment]
Great question! I'd probably need to know a little more about your daily setup as well as maybe a littler better insight into how you are doing the hand raising/permissions. In the meantime, I suggest posting this (and questions like this) to our [community forum](https://community.daily.co/). There will be more people available to help work through the problem with you there.

But before i close this without REALLY helping, two things that come to mind when reading your question:
1. if you have called `setLocalAudio/Video(true)` at some point in the call, `call.participants().local.tracks.audio.state` should report as `'blocked'` and you should be able to check that state to show them a message.
2. you might already be using it but if not, check out our new-ish [permissions API](https://docs.daily.co/reference/rn-daily-js/instance-methods/participants#participant-permissions-properties) may be useful for your use case in general (though not necessarily the blocked device problem)
