### ISSUE TITLE
supportedBrowser().supportsScreenShare returns 'true' for Chrome on Android

### ISSUE THREAD

**Issue by dbanisimov** [daily-co/daily-js#23]
I know that this static method is not documented (yet), but it seems like it incorrectly reports mobile chrome browsers as supporting screenshare.

As a workaround making a combined check `!supportedBrowser().mobile && supportedBrowser().supportsScreenShare` seems to give correct results, but I would expect from the original returned property to be a single source of truth for checking screenshare support.

**Comment by dbanisimov** [comment]
`supportsScreenShare` is now officially a part of the API, but it still reports Chrome on Android as supporting screenshare. Attempt to start a screenshare yields `DOMException: Invalid state`.

I guess this is a quirk of Chrome that `navigator.mediaDevices.getDisplayMedia` is defined, but not supported, so the way DailyCo detects the screenshare support is not fully correct: https://github.com/daily-co/daily-js/blob/03121091f26853c800277e3a43f0619d0d43b527/src/shared-with-pluot-core/Environment.js#L38-L44

**Comment by markbackman** [comment]
Confirmed that Chrome on Android accurately reports `supportsScreenShare` via the [`supportedBrowser()`](https://docs.daily.co/reference/daily-js/static-methods/supported-browser) method.

Example object returned on Chrome 120:
```
{
    "supported": true,
    "mobile": true,
    "name": "Chrome",
    "version": "120.0.0.0",
    "supportsFullscreen": true,
    "supportsScreenShare": false,
    "supportsSfu": true,
    "supportsVideoProcessing": false,
    "supportsAudioProcessing": false
}
```
