### ISSUE TITLE
`@daily-co/daily-js` v0.55.0 breaks types

### ISSUE THREAD

**Issue by ahkhanjani** [daily-co/daily-js#233]
The latest release does not recognize package types:

```
Could not find a declaration file for module '@daily-co/daily-js'. '***/node_modules/.pnpm/@daily-co+daily-js@0.55.0/node_modules/@daily-co/daily-js/dist/daily.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/daily-co__daily-js` if it exists or add a new declaration (.d.ts) file containing `declare module '@daily-co/daily-js';`ts(7016)
```

It's also not labeled as the latest release on GitHub releases. I'm reverting to v0.54.0 for the time being.

**Comment by mattieruth** [comment]
Thank you for flagging this! We are preparing a patch release and will re-release shortly.

**Comment by mattieruth** [comment]
0.55.1 is now released and should resolve these issues. thanks again.
