### ISSUE TITLE
daily-js 0.63 error on macOS Chrome ARM64 without graphics acceleration

### ISSUE THREAD

**Issue by johnwils** [daily-co/daily-js#251]
# Expected behavior

The 0.63 daily.js bundle should work with graphic acceleration turned off on macOS Chrome arm64 builds.

# Describe the bug (unexpected behavior)

On Chrome version 124.0.6367.119 (Official Build) (arm64), an error occurs preventing the camera from starting. Note: This issue is not reproducible on Intel builds of Chrome for macOS, only on arm64 builds.

# Steps to reproduce

1. Open Chrome 124.0.6367.119 (Official Build) (arm64)
2. Open settings and turn off "Use graphics acceleration when available".
3. Load a website with daily-js version 0.63
4. See error `call-machine-object-bundle.js:2 Uncaught TypeError: Cannot read properties of null (reading 'createTexture')`

# Screenshots

![error](https://github.com/daily-co/daily-js/assets/13921582/0b94069e-7a7e-4b79-935c-df4f799fff03)

<img width="748" alt="chrome" src="https://github.com/daily-co/daily-js/assets/13921582/7c53fc1b-468f-4eb1-a3e2-b9068be8c1b2">

# System information 

* Device: Macbook Pro 16-inch, 2021
* OS, version: macOS Sonoma 14.4.1 (23E224)
* Browser, version: Chrome 124.0.6367.119 (Official Build) (arm64)

# Additional context

This issue is not reproducible on daily-js versions 0.60, 0.61, or 0.62, in my testing. It appears only in version 0.63 and only on arm64 builds of Chrome on macOS.

**Comment by mattieruth** [comment]
Thank you for this report. We found this issue last week and have a fix that will go out in the next release, which should land today or tomorrow.

**Comment by mattieruth** [comment]
Closing this issue now that 0.64.0 has been released.
