### ISSUE TITLE
BUG | Daily Prebuilt | Unsent chat text disappears after switching to other Daily tab and back

### ISSUE THREAD

**Issue by mklepaczewski** [daily-co/daily-js#253]
# Expected behavior

When typing text into the chat box and then switching to the Network tab and back, I expect the unsent text to be still present in the chat box.

# Describe the bug (unexpected behavior)

The chat text is gone.

# Steps to reproduce

1. Connect to a room.
2. Open the chat tab
3. Type "test" but don't send it
4. Switch to Network tab
5. Switch back to the chat tab
6. Observe the "test" text is gone

# System information 

* Device: Windows PC, MacOS / other
* OS, version: Windows 10 
* Browser, version: Chrome 127.0.6533.73

# Additional context

It used to work that way. It's surprisingly annoying for our users as they use several custom integrations and they switch between them frequently.

**Comment by mattieruth** [comment]
Thank you for the report! We will look into this.

**Comment by mattieruth** [comment]
Thank you again for reporting this! We have confirmed the issue and deployed a fix.
