### ISSUE TITLE
@sentry/browser vulneribility

### ISSUE THREAD

**Issue by milo-** [daily-co/daily-js#258]
There's a vulnerability in the dependency @sentry/browser https://github.com/advisories/GHSA-593m-55hh-j8gv

Would it be possible for you to to update this dependency? Thanks!

**Comment by mattieruth** [comment]
Thanks milo. Your timing is impeccable. I'm working on resolving all vulnerabilities for the next release right now! I'll update this issue when that goes out.

**Comment by Regaddi** [comment]
Sentry has been updated as part of [0.73.0](https://github.com/daily-co/daily-js/releases/tag/daily-js-2024-10-31-0.73.0).
