### ISSUE TITLE
BUG: Tooltip used as label for customButton on small screen

### ISSUE THREAD

**Issue by acarlsen** [daily-co/daily-js#259]
# Expected behavior

We use customTrayButtions, example:

```
 customTrayButtons: {
      customButtonOne: {
        iconPath: 'path/to/icon',
        label: 'Share file',
        tooltip: 'Click here to upload files to the meeting',
      }
    },
```

Icon is displayed fine on normal size screen with correct label. We also expect label to be used on small screen when custom button is displayed in overflow menu popup.

# Describe the bug (unexpected behavior)

When custom button is shown in overflow menu on small screen, the tooltip text is used as label for icon, making the text to long to fit in the window (text is limited to one line).

# Steps to reproduce

1. Create custom button as example above
2. Join video metting, use chrome dev tools to force button to be displayed in "***" overflow menu popup.
3. See that the tooltip text is used as label for custom button.

# Screenshots

Normal screen (using correct label):
![Screenshot 2024-11-18 at 15 15 40](https://github.com/user-attachments/assets/97997b31-2d99-4f02-b145-16a7b2d009fb)

Small screen using tooltip as label:
![Screenshot 2024-11-18 at 15 16 05](https://github.com/user-attachments/assets/1c1e0909-e9a6-4621-9263-f21b83a3ec73)

# System information 

* Device: Macbook Pro M1
* OS, version: MacOS 15.1
* Browser, version: Chrome 131.0.6778.70 (arm64)

**Comment by mattieruth** [comment]
Thanks for the report! We will look into this and get back to you.

**Comment by Regaddi** [comment]
A fix for this has been released this week!
