### ISSUE TITLE
If Yandex browsed is supported?

### ISSUE THREAD

**Issue by Systerr** [daily-co/daily-js#32]
Hi. We started project for Russian region (as a first step). And a lot of users here using Yandex browser. Yandex browser just another Chrome based browser.

If any reason exists why it not supported?

https://github.com/daily-co/daily-js/blob/bb5a478c7156c76137a574442cf2e208f58eaa3a/src/module.js#L225:L241

**Comment by markbackman** [comment]
Unfortunately, Yandex is not a supported browser due to low browser usage market share.
