### ISSUE TITLE
Daily - get media stream error in chrome version > 81 

### ISSUE THREAD

**Issue by ViniciusGularte** [daily-co/daily-js#33]
getusermedia DevicesNotFoundError thrown in latest browsers

I found this error in a user,  i test in https://test.webrtc.org/ and all stats are ok except the Microphone, in other versions of navigators, works great, but in chrome 81 cause the exceptions below

the possible solution - > https://stackoverflow.com/questions/48378750/getusermedia-devicesnotfounderror-thrown-in-latest-browsers?noredirect=1&lq=1

![image](https://user-images.githubusercontent.com/25805846/81000798-2853d580-8e1d-11ea-9fbc-e5d942035186.png)

![WhatsApp Image 2020-05-04 at 15 24 45](https://user-images.githubusercontent.com/25805846/81001634-6e5d6900-8e1e-11ea-9792-d343426bf2f7.jpeg)

![image](https://user-images.githubusercontent.com/25805846/81001797-a5cc1580-8e1e-11ea-87e3-92c2e25be5e9.png)

**Comment by kwindla** [comment]
We are not able to reproduce this. Are you still seeing issues with your microphone in Chrome 81?
