### ISSUE TITLE
Unmute local audio with custom audioSource - reset audio back to default 

### ISSUE THREAD

**Issue by Systerr** [daily-co/daily-js#40]
Hi. We using  custom audioSource for audio. when audio muted all works great, but on onmute daily reinit camera and reset audio back to default. As a result this also generate "camera-error" event on safari browsers.

How it used on our way (our part of code
```javascript
const AC = window.AudioContext || window.webkitAudioContext;
const audioCtx = new AC();
const destinationStream = audioCtx.createMediaStreamDestination();

const callObject = DailyIframe.createCallObject({
      audioSource: destinationStream.stream.getAudioTracks()[0],
});
```

next we connectin mic to our audio system and all other nessesary audio system integration.

Muting and unmuting happens this way

```javascript
callObject.setLocalAudio(isMicMuted); // true or false depend of current state
```

I checked more deeply inside daily and daily call-machine code and inside the codebase on unmute enumeratedevices and try to match device with real devices and then reset it (as custom track not on devices)

``` javascript
// from call-machine-object-bundle.js
availableDevices = await navigator.mediaDevices.enumerateDevices()
if (audioDeviceId && audioDeviceId !== 'default') {
    if (!availableDevices.find(d => d.deviceId === audioDeviceId)) {
      console.log('previous audio device not found, switching to default');
      dispatch(updateLocalCam({ audioDeviceId: 'default' }));
}
```

could you please here add checking that 'audioDeviceId' is not a string and it a custom audio source.
Or maybe you have another way to add custom audio into call?

**Comment by kwindla** [comment]
Hi. Thank you for reporting this. We will create a reproduction test and a fix.

**Comment by kwindla** [comment]
Hi. This is fixed now. We really appreciate the bug report. Please contact us if you would like an account credit.
