### ISSUE TITLE
Ability to update local user name after join with predefined name in token

### ISSUE THREAD

**Issue by Systerr** [daily-co/daily-js#42]
in our integration we using predefined names into tokens by user also able to change name before join call. 

When i add username into join call then happens nothing - daily still uses username from token.

Expected behaviour  for user name priority
1) use from JOIN call.
2) if no in JOIN use from construstor.
3) if no from constructor - use from token.

**Comment by kwindla** [comment]
That's a very sensible suggestion. We'll look at this and see if there are any blockers to implementing this behavior.

**Comment by kwindla** [comment]
Hi,

I looked back at our notes for this feature, and the reason we don't allow userName to override a username if there's one in the meeting token is for security. Meeting tokens are signed and generated by your API key. So we don't want user-visible code to override the user_name field provided in the token.

Does that make sense? Is this a show-stopper issue for you?

Yours,
Kwin

**Comment by Systerr** [comment]
Yes this is stopper for us. 
Our case is:
we generate private rooms with two general tokens - one for owner and one for other users. Then link with token sending to users (one email who requested this 'meeting') and owner (one email to meeting organizer). Tokens have predefined names 'organizer' and 'participant' just in case to use meeting in one click. But user able to change predefined names on first screen to their names (optional). 

In our case 'meeting' have requesting by one user but inside meeting can participate multiple users with the same link.

As a solution  (to keep original name from token also) it can be - additional field (boolean) into token to allow override user name. Or special user name into token that apply as a last step

**Comment by Regaddi** [comment]
As of today this isn't an issue anymore: usernames can be changed after the fact, even when an original username was provided through a meeting token. In case the original username has to be maintained, a custom username override could be stored in [userData](https://docs.daily.co/reference/daily-js/instance-methods/set-user-data).
