### ISSUE TITLE
Listeners leak

### ISSUE THREAD

**Issue by kivutar** [daily-co/daily-js#47]
After calling `DailyIframe.createCallObject` and `join`, I notice a listeners leak:

<img width="794" alt="Screen Shot 2020-05-19 at 10 27 38" src="https://user-images.githubusercontent.com/442722/82284178-9a522000-99c2-11ea-9319-59038237aa4b.png">

I made sure that these functions were called only once, and I've also tried to not add any `on` callbacks. Still the same result.

This also happens on the `/hello` room.

<img width="711" alt="Screen Shot 2020-05-19 at 11 22 19" src="https://user-images.githubusercontent.com/442722/82284347-03399800-99c3-11ea-8a59-cb63c8a87e51.png">

**Comment by kwindla** [comment]
Thank you for reporting this. We will take a look. If you have a small repro case we’d appreciate it.

**Comment by kivutar** [comment]
Hi, any versions are affected, so https://demos.daily.co/static-demos/simple-demo/simple.html should be the way to go.

You can use the profiling tool of chrome, and record about 30seconds, it should be enough to notice the listeners curve.

**Comment by kwindla** [comment]
Ah, yes. This is a React issue and I believe that the listeners are garbage collected, but on a relatively slow timeline. It has not been an issue for us, and many of our customers do very long calls. But we will dig into this and see if we can reduce how many listeners are added by our React components.

Here is a 5 minute long recording:

<img width="1492" alt="Screenshot 2020-05-19 05 19 17" src="https://user-images.githubusercontent.com/7378232/82325807-ac1acf80-9990-11ea-8568-2847dabe5bea.png">
