### ISSUE TITLE
Not able to disable active speaker mode

### ISSUE THREAD

**Issue by Systerr** [daily-co/daily-js#61]
Hi. This mode enabled by default in case i use 'callObject' mode. And i not able to disable it

setActiveSpeakerMode(false) not disabling it, evens still fired

![image](https://user-images.githubusercontent.com/1553394/83571193-03dc3d80-a530-11ea-93d6-ac5318d1291f.png)

**Comment by kwindla** [comment]
Hi,

`setActiveSpeakerMode()` controls the UI mode for our pre-built user interface. It switches between "grid mode" and large/focused active speaker mode.

You will see `active-speaker-change` events even in call object mode. You don't have to install an event handler for those events if you don't want to use them. You can just ignore them. But they are available in case you want to make use of the active speaker information in your own UI.

Does that make sense?

**Comment by Systerr** [comment]
Hi. Thank you for you reply. 
My point i want to disable that feature completely (performance reason). Maybe it not produce load at all, but it exists all time and i not able to disable it

**Comment by kwindla** [comment]
Hi, the active speaker analysis doesn't create any significant additional cpu load.
