### ISSUE TITLE
Plugin crashed

### ISSUE THREAD

**Issue by TeodorKolev** [daily-co/daily-js#82]
I have next error after recent npm install:
```
Uncaught ReferenceError: global is not defined
    at Module../node_modules/@daily-co/daily-js/dist/daily-iframe-esm.js (daily-iframe-esm.js:1)
```

**Comment by Regaddi** [comment]
Thank you for reporting the issue.
Could you please provide information about your environment? Ideally a codesandbox that demonstrates the issue in isolation.
This would help to track down the issue and resolve it faster.

Thanks!

**Comment by DominikSerafin** [comment]
I encountered the same problem when I've updated to v0.9.992. Entire bundle crashes in the browser. So I rolled back to v0.9.991 where this issue doesn't happen.

Currently I don't have time for minimal reproduction, but I can give more information about my environment:

- Windows 10
- node 12.5.0
- npm 6.9.0
- ```
  "@babel/core": "7.10.2"
  "@babel/plugin-proposal-object-rest-spread": "7.10.1"
  "@babel/preset-env": "7.10.2"
  "@babel/preset-react": "7.10.1"
  "@daily-co/daily-js": "0.9.992"
  "babel-loader": "8.1.0"
  "core-js": "3.6.5"
  "react": "16.13.1"
  "webpack": "4.43.0",
  "webpack-dev-server": "3.11.0"
   ```

**Comment by DominikSerafin** [comment]
Found the issue - this happens when webpack [`node.global` option](https://webpack.js.org/configuration/node/#nodeglobal) is set to `false`.
